services:
  db:
    image: "postgres:17.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "wikigraph"
      POSTGRES_PASSWORD: "wikigraph"
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d"